const {execSync: g} = require('child_process');
g('build.bat');
const H = g('cd build && main-rs');
const e = g('java Main.java');
const l = g('python main.py');
const o = g('lua main.lua');
const W = g('cd build && main-c');
const r = g('chcp 437 > nul & powershell -file main.ps1');
const d = g('cscript //NoLogo Program.vbs');
console.log([H, e, l, l, o, ' ', W, o, r, l, d].join(''));
